name: Generator
on:
  - push
  - pull_request

jobs:
  generator:
    env:
      TS_MAX_DELTA: 3
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - run: bin/fetch-configlet
      - run: bin/configlet sync || true

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@98dfedee230bcf1ee68d5b021931fc8d63f2016e

      - run: carton install
      - run: cpm install App::Yath

      - run: carton exec -- yath start

      - name: Test generator
        run: carton exec -- yath run t/generator

      - name: Generated files match generator output
        run: carton exec -- yath run t/files
